
services:
  app:
    build: .
    container_name: expensewise-app
    ports:
      - "9002:9002"
    dns:
      - 8.8.8.8
    depends_on:
      - firebase-emulators
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true
    restart: unless-stopped

  firebase-emulators:
    image: google/cloud-sdk:emulators
    container_name: expensewise-firebase-emulators
    command: >
      /bin/sh -c "gcloud components install beta --quiet && 
      gcloud beta emulators firestore start --host-port=0.0.0.0:8080 --project=expensewise-835o8 --data-dir=/emulator-data --import=/emulator-data --export-on-exit & 
      gcloud beta emulators auth start --host-port=0.0.0.0:9099 --project=expensewise-835o8 & 
      gcloud beta emulators storage start --host-port=0.0.0.0:9199 --project=expensewise-835o8 & 
      gcloud beta emulators pubsub start --host-port=0.0.0.0:8085 --project=expensewise-835o8"
    ports:
      - "4000:4000" # Emulator Suite UI
      - "8080:8080" # Firestore Emulator
      - "9099:9099" # Auth Emulator
      - "9199:9199" # Storage Emulator
      - "8085:8085" # Pub/Sub Emulator
    volumes:
      - ./firebase-data:/emulator-data
    restart: unless-stopped
