services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      # This tells the app to connect to the emulators using the service name.
      - DOCKER_ENV=true
    depends_on:
      - firebase-emulators

  firebase-emulators:
    image: google/cloud-sdk:emulators
    ports:
      - '4000:4000' # UI
      - '8080:8080' # Firestore
      - '9099:9099' # Auth
      - '9199:9199' # Storage
    command: >
      gcloud emulators firestore start --host-port=0.0.0.0:8080
