services:
  app:
    build: .
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
      # This tells the app to connect to the emulators using the service name.
      - DOCKER_ENV=true
    depends_on:
      - firebase-emulators

  firebase-emulators:
    image: us-docker.pkg.dev/firebase-emulators/public/emulators:latest
    ports:
      - '4000:4000' # UI
      - '8080:8080' # Firestore
      - '9099:9099' # Auth
      - '9199:9199' # Storage
    command: >
      emulators:start --only auth,firestore,storage --import /app/seed_data --export-on-exit /app/seed_data
    volumes:
      - ./seed_data:/app/seed_data
